---
- name: update-first-time
  hosts: all
  become: true
  tasks:
    - name: update-apt-repo
      apt:
        update_cache: yes
        
          #   - name: put-public-key-in-authorized-keys-of-every-server
          #     authorized_key:
          #       user: ubuntu
          #       state: present

    - name: create user rohit
      user:
        user: rohit
        groups: root
