- hosts: ubuntu_slaves
  become: true
  tasks:
    - name: copy built files to deploy-server
      synchronize:
        src: /var/lib/jenkins/workspace/node-pipeline1/build/
        dest: /var/www/my-app/
        delete: true
        recursive: true

    - name: start node
      shell: startnode.sh
      args:
        chdir: /var/www/my-app/

  
