- hosts: ubuntu_slaves
  become: true
  tasks:
    - name: copy built files to deploy-server
      copy:
        src: /var/lib/jenkins/workspace/node-pipeline/ 
        dest: /var/www/my-app/
        mode: 0755
        owner: root
        group: root

    - name: start node
      shell:
        cmd: npm i && npm i pm2@latest && pm2 start
        chdir: /var/www/my-app/

  
